### ISSUE TITLE
action always undefined

### ISSUE THREAD

**Issue by maosmurf** [oaf-project/oaf-next.js-router#24] opened 2019-12-10 14:44 UTC
Hey,

because of [index.ts#L48](https://github.com/oaf-project/oaf-next.js-router/blob/master/src/index.ts#L48) the value of `action` is always `undefined`.
Therefore in [oaf-router.ts#L162](https://github.com/oaf-project/oaf-routing/blob/master/src/oaf-router.ts#L162) the block `if (shouldRestorePageState)` is never reached.

How can we provide an action for `oaf-routing` from next.js ?

**Comment by danielnixon** [comment] 2019-12-10 21:26
Hi @maosmurf,

You're right.

Sadly, unlike some other routers, Next's router _does not_ give us that information (i.e. it doesn't tell us whether a route change was a caused by a push or a pop).

I have some ideas about getting that info by (ab)using the [history](https://www.npmjs.com/package/history) package. You'll see a speculative TODO for that just above the line in your first link.

**Comment by danielnixon** [comment] 2019-12-10 21:27
Duplicate of #1

**Closed as completed by danielnixon** 2019-12-10 21:27 UTC
